namespace OrangeJuiceBot.Model
{
    public enum Card
    {
        Unknown,

        // Boost
        Dash,
        SakisCookie,
        FlipOut,
        LongDistanceShot,
        NiceJingle,
        NicePresent,
        StiffCrystal,
        Pudding,
        Extend,
        PrincesssPrivilege,
        LonelyChariot,
        Ambush,
        PassionateResearch,
        PresidentsPrivilege,
        Mimic,
        CompletionReward,
        GentlemansBattle,

        // Battle
        ImOnFire,
        Rbits,
        RainbowColoredCircle,
        BigMagnum,
        Shield,
        FinalBattle,
        ReverseAttributeField,
        TacticalRetreat,
        ShieldCounter,
        AccelHyper,
        Extension,
        QuickRestoration,

        // Trap
        BadPudding,
        MimyuusHammer,
        DangerousPudding,
        PiggyBank,
        Invasion,
        GoAway,
        Heat300,
        Assault,
        TragedyInTheDeadNight,
        Exchange,
        FlameThrower,
        SkyRestaurantPures,
        ForTheFutureOfTheToyStore,
        PiyopiyoProcession,
        SealedMemories,
        BrutalPrank,
        PresentThief,

        // Event
        HereAndThere,
        CloudOfSeagulls,
        HolyNight,
        OutOfAmmo,
        GiftExchange,
        WeAreWaruda,
        Dinner,
        SuperAllOutMode,
        ForcedRevival,
        LittleWar,
        OhMyFriend,
        SealedGuardian,
        MixPhenomenon,
        ScarySolicitation,
        PlayOfTheGods,
        ScrambledEve,
        StarBlastingLight,

        // Gift
        UnLuckyCharm,
        WindyEnchantment,

        // Hyper
        ExtraordinarySpecs,
        X16BigRocket,
        ProtagonistsPrivilege,
        Ubiquitous,
        SweetGuardian,
        CastOff,
        Blazing,
        CrystalBarrier,
        JonathanRush,
        HyperMode,
        BlueCrowTheSecond,
        BeyondHell,
        DeployBits,
        SelfDestruct,
        ReflectiveShell,
        AnotherUltimateWeapon,
        WarudaMachineBlastOff,
        BigBangBell,
        DanceLongEaredBeasts,
        InvisibleBomb,
        GoldenEgg,
        Gamble,
        PresentForYou,
        BindingChains,
        AirStrike,
        MagicalMassacre,
        PlushieMaster,
        DeltaField,
        WhimsicalWindmill,
        EvilSpyWorkPreparation,
        BannedForLife,
        EvilSpyWorkExecution,
        StarBlastingFuse,
        MeltingMemories
    }
}